version: 2.1
orbs:
  newman: postman/newman@0.0.2
  discord: antonioned/discord@0.1.0
jobs:
  PS5-Stock:
    executor: newman/postman-newman-docker
    steps:
      - checkout
      - run:
         command: apk update; apk add bash curl curl-dev
      - newman/newman-run:
          collection: ./Stock.postman_collection.json
      - discord/status:
          fail_only: true
          success_message: "Found PS5 Stock.
          [][][][][][][][] https://www.thewarehouse.co.nz/p/ps5-console/R2695122.html 
          [][][][][][][][] https://www.thewarehouse.co.nz/p/ps5-playstation-5-digital-edition/R2695123.html
          [][][][][][][][] https://www.noelleeming.co.nz/shop/games-gaming/playstation/playstation-5/playstation-5-cfi-1015a-console/prod192865.html
          [][][][][][][][] https://www.noelleeming.co.nz/shop/games-gaming/playstation/playstation-5/playstation-5-cfi-1015b-digital-edition-console/prod192879.html"
          failure_message: "Found PS5 Stock.
          [][][][][][][][] https://www.thewarehouse.co.nz/p/ps5-console/R2695122.html 
          [][][][][][][][] https://www.thewarehouse.co.nz/p/ps5-playstation-5-digital-edition/R2695123.html
          [][][][][][][][] https://www.noelleeming.co.nz/shop/games-gaming/playstation/playstation-5/playstation-5-cfi-1015a-console/prod192865.html
          [][][][][][][][] https://www.noelleeming.co.nz/shop/games-gaming/playstation/playstation-5/playstation-5-cfi-1015b-digital-edition-console/prod192879.html"
          webhook: "${DISCORD_STATUS_WEBHOOK}"
workflows:
  version: 2
  build_and_test:
    jobs:
      - PS5-Stock
  daily:
    triggers:
      - schedule:
          cron: "0,5,10,15,20,25,30,35,40,45,50,55 22,23,0,1,2,3,4,5 * * *"
          filters:
            branches:
              only:
                - main
    jobs:
      - PS5-Stock