version: 2.1
orbs:
  newman: postman/newman@0.0.2
  discord: antonioned/discord@0.1.0
jobs:
  newman-collection-run:
    executor: newman/postman-newman-docker
    steps:
      - checkout
      - run:
         command: apk update; apk add bash curl curl-dev
      - newman/newman-run:
          collection: ./Stock.postman_collection.json
      - discord/status:
          fail_only: false
          failure_message: "**${CIRCLE_USERNAME}**'s build: **${CIRCLE_JOB}** failed."
          webhook: "${DISCORD_STATUS_WEBHOOK}"
workflows:
  version: 2
  build_and_test:
    jobs:
      - newman-collection-run
  daily:
    triggers:
      - schedule:
          cron: "0,5,10,15,20,25,30,35,40,45,50,55 10 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - newman-collection-run